// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.progsquad.chessmanager.model;

import org.springframework.beans.factory.annotation.Configurable;
import ro.progsquad.chessmanager.model.TeamMatchIntegrationTest;

privileged aspect TeamMatchIntegrationTest_Roo_Configurable {
    
    declare @type: TeamMatchIntegrationTest: @Configurable;
    
}
